### ISSUE TITLE
Fluidsynth version/madmom.loadAudioFileError

### ISSUE THREAD

**Issue by gszswork** [CPJKU/audio_conditioned_unet#1]
Can you share the fluidsynth version of your code?
I have run your project "score_following_game" and "audio_conditioned_unet". The following error (madam loadAudio file error) occurred in both runs. I tried on MacOX and linux and there is no difference. After checking the environment I guess the problem may locate at the fluidsynth. On my computer I installed the fluidsynth2.14. Thanks in advance :)

`fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
Traceback (most recent call last):
  File "test_model.py", line 42, in <module>
    real_perf=config['real_perf'])
  File "/Users/szg/Downloads/audio_conditioned_unet/audio_conditioned_unet/utils.py", line 128, in load_song
    real_perf=real_perf)
  File "/Users/szg/Downloads/audio_conditioned_unet/audio_conditioned_unet/utils.py", line 172, in load_performance
    spec = midi_to_spec_otf(midi, spectrogram_params, sound_font_path=sf_path)
  File "/Users/szg/Downloads/audio_conditioned_unet/audio_conditioned_unet/utils.py", line 85, in midi_to_spec_otf
    spec = processor.process(audio_path).T
  File "/Users/szg/anaconda3/envs/audio_conditioned_unet/lib/python3.7/site-packages/madmom/processors.py", line 424, in process
    data = _process((processor, data, kwargs))
  File "/Users/szg/anaconda3/envs/audio_conditioned_unet/lib/python3.7/site-packages/madmom/processors.py", line 289, in _process
    return process_tuple[0](*process_tuple[1:-1], **process_tuple[-1])
  File "/Users/szg/anaconda3/envs/audio_conditioned_unet/lib/python3.7/site-packages/madmom/processors.py", line 120, in __call__
    return self.process(*args, **kwargs)
  File "/Users/szg/anaconda3/envs/audio_conditioned_unet/lib/python3.7/site-packages/madmom/audio/signal.py", line 769, in process
    return Signal(data, **args)
  File "/Users/szg/anaconda3/envs/audio_conditioned_unet/lib/python3.7/site-packages/madmom/audio/signal.py", line 598, in __new__
    dtype=dtype)
  File "/Users/szg/anaconda3/envs/audio_conditioned_unet/lib/python3.7/site-packages/madmom/io/audio.py", line 633, in load_audio_file
    raise LoadAudioFileError(error)
madmom.io.audio.LoadAudioFileError: "All attempts to load audio file '/var/folders/79/26vt9yzn6w15mqnqw7x2l9fw0000gn/T/1598287327.53145.wav' failed. Try installing ffmpeg (or avconv on Ubuntu Linux)."
`

**Comment by fhenkel** [comment]
We used Fluidsynth 1.1.9 on an Ubuntu 18.04 machine.
